# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\x12\x03\x61pp\"\x1b\n\x07\x41\x63\x63ount\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1a\n\nUserSearch\x12\x0c\n\x04text\x18\x01 \x01(\t\":\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"3\n\x0fSuccessResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe8\x02\n\x03\x41pp\x12\x35\n\rCreateAccount\x12\x0c.app.Account\x1a\x14.app.SuccessResponse\"\x00\x12-\n\x05LogIn\x12\x0c.app.Account\x1a\x14.app.SuccessResponse\"\x00\x12.\n\x06LogOut\x12\x0c.app.Account\x1a\x14.app.SuccessResponse\"\x00\x12\x31\n\x0cListAccounts\x12\x0f.app.UserSearch\x1a\x0c.app.Account\"\x00\x30\x01\x12\x33\n\x0bSendMessage\x12\x0c.app.Message\x1a\x14.app.SuccessResponse\"\x00\x12,\n\nGetMessage\x12\x0c.app.Account\x1a\x0c.app.Message\"\x00\x30\x01\x12\x35\n\rDeleteAccount\x12\x0c.app.Account\x1a\x14.app.SuccessResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCOUNT._serialized_start=18
  _ACCOUNT._serialized_end=45
  _USERSEARCH._serialized_start=47
  _USERSEARCH._serialized_end=73
  _MESSAGE._serialized_start=75
  _MESSAGE._serialized_end=133
  _SUCCESSRESPONSE._serialized_start=135
  _SUCCESSRESPONSE._serialized_end=186
  _APP._serialized_start=189
  _APP._serialized_end=549
# @@protoc_insertion_point(module_scope)
